# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vbox/equihash-beam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vbox/equihash-beam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vbox/equihash-beam/CMakeFiles /home/vbox/equihash-beam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vbox/equihash-beam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named beam_shared

# Build rule for target.
beam_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beam_shared
.PHONY : beam_shared

# fast build rule for target.
beam_shared/fast:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/build
.PHONY : beam_shared/fast

src/beamHashIII_imp.o: src/beamHashIII_imp.cpp.o

.PHONY : src/beamHashIII_imp.o

# target to build an object file
src/beamHashIII_imp.cpp.o:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/beamHashIII_imp.cpp.o
.PHONY : src/beamHashIII_imp.cpp.o

src/beamHashIII_imp.i: src/beamHashIII_imp.cpp.i

.PHONY : src/beamHashIII_imp.i

# target to preprocess a source file
src/beamHashIII_imp.cpp.i:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/beamHashIII_imp.cpp.i
.PHONY : src/beamHashIII_imp.cpp.i

src/beamHashIII_imp.s: src/beamHashIII_imp.cpp.s

.PHONY : src/beamHashIII_imp.s

# target to generate assembly for a file
src/beamHashIII_imp.cpp.s:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/beamHashIII_imp.cpp.s
.PHONY : src/beamHashIII_imp.cpp.s

src/blake/blake2b.o: src/blake/blake2b.cpp.o

.PHONY : src/blake/blake2b.o

# target to build an object file
src/blake/blake2b.cpp.o:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/blake/blake2b.cpp.o
.PHONY : src/blake/blake2b.cpp.o

src/blake/blake2b.i: src/blake/blake2b.cpp.i

.PHONY : src/blake/blake2b.i

# target to preprocess a source file
src/blake/blake2b.cpp.i:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/blake/blake2b.cpp.i
.PHONY : src/blake/blake2b.cpp.i

src/blake/blake2b.s: src/blake/blake2b.cpp.s

.PHONY : src/blake/blake2b.s

# target to generate assembly for a file
src/blake/blake2b.cpp.s:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/blake/blake2b.cpp.s
.PHONY : src/blake/blake2b.cpp.s

src/equihashR_imp.o: src/equihashR_imp.cpp.o

.PHONY : src/equihashR_imp.o

# target to build an object file
src/equihashR_imp.cpp.o:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/equihashR_imp.cpp.o
.PHONY : src/equihashR_imp.cpp.o

src/equihashR_imp.i: src/equihashR_imp.cpp.i

.PHONY : src/equihashR_imp.i

# target to preprocess a source file
src/equihashR_imp.cpp.i:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/equihashR_imp.cpp.i
.PHONY : src/equihashR_imp.cpp.i

src/equihashR_imp.s: src/equihashR_imp.cpp.s

.PHONY : src/equihashR_imp.s

# target to generate assembly for a file
src/equihashR_imp.cpp.s:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/equihashR_imp.cpp.s
.PHONY : src/equihashR_imp.cpp.s

src/lib.o: src/lib.cpp.o

.PHONY : src/lib.o

# target to build an object file
src/lib.cpp.o:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/lib.cpp.o
.PHONY : src/lib.cpp.o

src/lib.i: src/lib.cpp.i

.PHONY : src/lib.i

# target to preprocess a source file
src/lib.cpp.i:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/lib.cpp.i
.PHONY : src/lib.cpp.i

src/lib.s: src/lib.cpp.s

.PHONY : src/lib.s

# target to generate assembly for a file
src/lib.cpp.s:
	$(MAKE) -f CMakeFiles/beam_shared.dir/build.make CMakeFiles/beam_shared.dir/src/lib.cpp.s
.PHONY : src/lib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... beam_shared"
	@echo "... src/beamHashIII_imp.o"
	@echo "... src/beamHashIII_imp.i"
	@echo "... src/beamHashIII_imp.s"
	@echo "... src/blake/blake2b.o"
	@echo "... src/blake/blake2b.i"
	@echo "... src/blake/blake2b.s"
	@echo "... src/equihashR_imp.o"
	@echo "... src/equihashR_imp.i"
	@echo "... src/equihashR_imp.s"
	@echo "... src/lib.o"
	@echo "... src/lib.i"
	@echo "... src/lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

